version: "2"
services:
  cards:
    image: node:argon
    ports:
      - "3000:8080"
    volumes:
      - ./rune-card-service:/app
    working_dir: /app
    command: npm start
    links:
      - cards-db
  cards-db:
    image: mongo:3
  cards-seed:
    image: node:argon
    volumes:
      - ./rune-card-service-seed:/app
    working_dir: /app
    command: npm start
    links:
      - cards-db
  collections:
    image: node:argon
    ports:
      - "3001:8080"
    volumes:
      - ./rune-collection-service:/app
    working_dir: /app
    command: npm start
    links:
      - collections-db
  collesctions-db:
    image: mongo:3
