version: "2"
services:
  cards:
    image: node:boron
    ports:
      - "3000:8080"
    volumes:
      - ./rune-card-service:/app
    working_dir: /app
    command: npm start
    links:
      - card-db
  card-db:
    image: mongo:3
  cards-seed:
    image: node:boron
    volumes:
      - ./rune-card-service-seed:/app
    working_dir: /app
    command: npm start
    links:
      - card-db
  collections:
    image: node:boron
    ports:
      - "3001:8080"
    volumes:
      - ./rune-collection-service:/app
    working_dir: /app
    command: npm start
    links:
      - collection-db
  collection-db:
    image: mongo:3
  ui:
    image: node:boron
    ports:
      - "8080:3000"
    volumes:
      - ./rune-ui:/app
    working_dir: /app
    command: npm start
